language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgl1-mesa-dev
  - sudo apt-get install -y xorg-dev

install:
  - make install

script:
  - make test
